//Header Generated with https://github.com/aiekick/ImGuiFontStudio
//Based on https://github.com/juliettef/IconFontCppHeaders

#pragma once

#define FONT_ICON_BUFFER_NAME_IGFS IGFS_compressed_data_base85
#define FONT_ICON_BUFFER_SIZE_IGFS 0x27fb

#define ICON_MIN_IGFS 0xf002
#define ICON_MAX_IGFS 0xf3a0

#define ICON_IGFS_ABOUT u8"\uf129"
#define ICON_IGFS_ADD u8"\uf067"
#define ICON_IGFS_BY_CODEPOINT u8"\uf3a0"
#define ICON_IGFS_BY_FONT u8"\uf031"
#define ICON_IGFS_BY_NAME u8"\uf02c"
#define ICON_IGFS_CANCEL u8"\uf00d"
#define ICON_IGFS_COLUMNS u8"\uf0db"
#define ICON_IGFS_COPY u8"\uf0c5"
#define ICON_IGFS_CUT u8"\uf0c4"
#define ICON_IGFS_DESTROY u8"\uf014"
#define ICON_IGFS_DRIVES u8"\uf233"
#define ICON_IGFS_EDIT u8"\uf040"
#define ICON_IGFS_ERROR u8"\uf057"
#define ICON_IGFS_EXCLAMATION u8"\uf12a"
#define ICON_IGFS_FILE u8"\uf016"
#define ICON_IGFS_FILE_TYPE_PROJECT u8"\uf1c4"
#define ICON_IGFS_FILE_TYPE_TEXT u8"\uf0f6"
#define ICON_IGFS_FILTER u8"\uf0b0"
#define ICON_IGFS_FOLDER u8"\uf114"
#define ICON_IGFS_FOLDER_OPEN u8"\uf115"
#define ICON_IGFS_FULLSCREEN u8"\uf0b2"
#define ICON_IGFS_GENERATE u8"\uf085"
#define ICON_IGFS_GLYPHS u8"\uf003"
#define ICON_IGFS_HELP u8"\uf128"
#define ICON_IGFS_ICON_EDIT u8"\uf14b"
#define ICON_IGFS_ICON_VIEW u8"\uf0c8"
#define ICON_IGFS_INFOS u8"\uf05a"
#define ICON_IGFS_LAYOUT u8"\uf26c"
#define ICON_IGFS_LINK u8"\uf1c9"
#define ICON_IGFS_MENU_LEFT u8"\uf0d9"
#define ICON_IGFS_MENU_RIGHT u8"\uf0da"
#define ICON_IGFS_MENU_UP u8"\uf0d8"
#define ICON_IGFS_OK u8"\uf00c"
#define ICON_IGFS_PASTE u8"\uf0ea"
#define ICON_IGFS_PROJECT u8"\uf02d"
#define ICON_IGFS_REDO u8"\uf01e"
#define ICON_IGFS_REFRESH u8"\uf021"
#define ICON_IGFS_REMOVE u8"\uf068"
#define ICON_IGFS_RESET u8"\uf064"
#define ICON_IGFS_SAVE u8"\uf0c7"
#define ICON_IGFS_SEARCH u8"\uf002"
#define ICON_IGFS_SELECT u8"\uf245"
#define ICON_IGFS_SELECT_PATH u8"\uf0d0"
#define ICON_IGFS_SETTINGS u8"\uf1de"
#define ICON_IGFS_SORT_ASC u8"\uf077"
#define ICON_IGFS_SORT_DESC u8"\uf078"
#define ICON_IGFS_TARGET u8"\uf05b"
#define ICON_IGFS_TEXTURE u8"\uf03e"
#define ICON_IGFS_UNDO u8"\uf0e2"
#define ICON_IGFS_WARNING u8"\uf071"
