name: Win_Vulkan

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build_Win_2016:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install Vulkan lib / Requirement for Glfw3
      run : vcpkg install vulkan:x86-windows 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_VULKAN=on
    - name: build
      run: cmake --build build --config RelWithDebInfo
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFontStudio_Msvc_x32
        path: build\RelWithDebInfo\ImGuiFontStudio_Msvc_x32.exe
