name: Linux_Vulkan

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build_Linux_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install Vulkan lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils libvulkan-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_VULKAN=on
    - name: build
      run: cmake --build build
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFontStudio_x32
        path: build/ImGuiFontStudio_x32
